[package]
name = "monero_miner"
version = "0.1.0"
edition = "2021"
description = "A Monero miner written in Rust"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
obfstr = "0.4.3"
reqwest = "0.11"
tokio = { version = "1", features = ["full"] }
zip = "0.6.6"


[package.metadata.bundle]
name = "MoneroMiner" # The name of your application
version = "0.1.0" # The version of your application
authors = ["Bader alotaibi baderalotaibi3@gmail.com"] # List of authors
description = "A Monero miner written in Rust" # A description of your application
license = "MIT" # The license of your application

